name: ML
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - abseil-cpp=20211102.0=hc377ac9_0
  - absl-py=2.1.0=py39hca03da5_0
  - aiohappyeyeballs=2.4.0=py39hca03da5_0
  - aiohttp=3.10.5=py39h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - alabaster=0.7.16=py39hca03da5_0
  - annotated-types=0.6.0=py39hca03da5_0
  - aom=3.6.0=h313beb8_0
  - app-model=0.3.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - asciitree=0.3.3=py_2
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - async-timeout=4.0.3=py39hca03da5_0
  - attrs=23.1.0=py39hca03da5_0
  - babel=2.16.0=py39hca03da5_0
  - biopython=1.78=py39h1a28f6b_0
  - blas=1.0=openblas
  - blinker=1.6.2=py39hca03da5_0
  - blosc=1.21.6=h7977b18_0
  - bottleneck=1.3.7=py39hbda83bc_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py39h313beb8_8
  - brunsli=0.1=hc377ac9_1
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2025.7.15=hca03da5_0
  - cachetools=5.3.3=py39hca03da5_0
  - cachey=0.2.1=pyh9f0ad1d_0
  - certifi=2025.8.3=py39hca03da5_0
  - cffi=1.17.1=py39h3eb5a62_0
  - cfitsio=3.470=h7f6438f_7
  - charls=2.2.0=hc377ac9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py39hca03da5_0
  - cloudpickle=3.1.1=py39hca03da5_0
  - colorama=0.4.6=py39hca03da5_0
  - comm=0.2.2=pyhd8ed1ab_0
  - cryptography=41.0.3=py39h3c57c4d_0
  - cytoolz=1.0.1=py39h80987f9_0
  - dask-core=2024.5.0=py39hca03da5_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.6.7=py39h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docstring_parser=0.16=py39hca03da5_0
  - docutils=0.21.2=py39hca03da5_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.7.1=h313beb8_0
  - fasteners=0.20=py39hca03da5_0
  - flatbuffers=24.3.25=h313beb8_0
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - fontconfig=2.14.1=hee714a5_2
  - freetype=2.12.1=h1192e45_0
  - freetype-py=2.2.0=pyhd3eb1b0_0
  - frozenlist=1.4.0=py39h80987f9_0
  - gast=0.4.0=pyhd3eb1b0_0
  - ghostscript=10.04.0=hf9b8971_0
  - giflib=5.2.1=h80987f9_3
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py39h8c48613_0
  - google-auth=2.29.0=py39hca03da5_0
  - google-auth-oauthlib=0.5.2=py39hca03da5_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=h877324c_0
  - grpcio=1.48.2=py39h877324c_0
  - h5py=3.11.0=py39haafd478_0
  - hdf5=1.12.1=h160e8cb_2
  - heapdict=1.0.1=pyhd3eb1b0_0
  - hsluv=5.0.3=py39hca03da5_0
  - icu=68.1=hc377ac9_0
  - imagecodecs=2023.1.23=py39h604db08_0
  - imageio=2.37.0=py39hca03da5_0
  - imagesize=1.4.1=py39hca03da5_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.0=py39hca03da5_0
  - in-n-out=0.2.1=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=py39hca03da5_0
  - joblib=1.4.2=py39hca03da5_0
  - jpeg=9e=h80987f9_3
  - jsonschema=4.25.0=py39hca03da5_0
  - jsonschema-specifications=2023.7.1=py39hca03da5_0
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hca03da5_0
  - jxrlib=1.1=h1a28f6b_2
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - krb5=1.20.1=h8380606_1
  - lazy_loader=0.4=py39hca03da5_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libaec=1.1.3=h313beb8_0
  - libavif=0.11.1=h80987f9_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcurl=8.2.1=h0f1d93c_0
  - libcxx=19.1.0=ha82da77_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h80987f9_3
  - libllvm14=14.0.6=h19fdd8a_4
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.10.0=h449679c_2
  - libtiff=4.5.1=h313beb8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h372ba2a_0
  - libzlib=1.2.13=hfb2fe0b_6
  - libzopfli=1.0.3=hc377ac9_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - llvmlite=0.43.0=py39h313beb8_1
  - locket=1.0.0=py39hca03da5_0
  - lz4-c=1.9.4=h313beb8_1
  - magicgui=0.10.1=pyhd8ed1ab_0
  - markdown=3.4.1=py39hca03da5_0
  - markupsafe=2.1.3=py39h80987f9_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py39hca03da5_0
  - msgpack-python=1.1.1=py39h313beb8_0
  - multidict=6.0.4=py39h80987f9_0
  - napari=0.5.6=pyhd8ed1ab_0
  - napari-base=0.5.6=pyh9208f05_0
  - napari-console=0.1.3=pyh73487a3_0
  - napari-plugin-engine=0.2.0=pyha07c04f_3
  - napari-plugin-manager=0.1.4=pyha07c04f_0
  - napari-svg=0.2.1=pyha07c04f_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.2.1=py39hca03da5_0
  - npe2=0.7.9=pyhd8ed1ab_0
  - numba=0.60.0=py39h313beb8_1
  - numcodecs=0.12.1=py39h1a4646a_0
  - numexpr=2.8.7=py39hecc3335_0
  - numpydoc=1.9.0=py39hd096484_0
  - oauthlib=3.2.2=py39hca03da5_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=1.1.1w=h1a28f6b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py39h313beb8_0
  - parso=0.8.4=pyhd8ed1ab_0
  - partd=1.4.2=py39hca03da5_0
  - pbzip2=1.1.13=h8e2fd4a_2
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py39h80987f9_0
  - pint=0.24.4=pyhe01879c_2
  - pip=24.2=py39hca03da5_0
  - platformdirs=4.3.2=pyhd8ed1ab_0
  - pooch=1.8.2=py39hca03da5_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - protobuf=3.20.3=py39h313beb8_0
  - psutil=5.8.0=py39h5161555_1
  - psygnal=0.12.0=py39hca03da5_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd3eb1b0_1
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py39hca03da5_0
  - pydantic-compat=0.1.2=pyhd8ed1ab_0
  - pydantic-core=2.33.2=py39h5e3a92f_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.8.0=py39hca03da5_0
  - pyopengl=3.1.9=py39hca03da5_0
  - pyopenssl=23.2.0=py39hca03da5_0
  - pyproject_hooks=1.0.0=py39hca03da5_0
  - pysocks=1.7.1=py39hca03da5_0
  - python=3.9.18=hc0d8a6c_0
  - python-build=1.3.0=py39hca03da5_0
  - python-dotenv=1.1.0=py39hca03da5_0
  - python-flatbuffers=24.3.25=py39hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=2.3.0=cpu_py39h10d1568_0
  - pyyaml=6.0.2=py39h80987f9_0
  - pyzmq=25.1.2=py39h313beb8_0
  - qtconsole-base=5.6.1=pyha770c72_2
  - qtpy=2.4.1=py39hca03da5_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py39hca03da5_0
  - requests=2.32.3=py39hca03da5_0
  - requests-oauthlib=2.0.0=py39hca03da5_0
  - rpds-py=0.22.3=py39h2aea54e_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scikit-image=0.24.0=py39h46d7db6_0
  - scikit-learn=1.5.1=py39h46d7db6_0
  - scipy=1.13.1=py39hd336fd7_1
  - seaborn=0.13.2=py39hca03da5_0
  - setuptools=72.1.0=py39hca03da5_0
  - shellingham=1.5.0=py39hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h80987f9_2
  - snappy=1.2.1=h313beb8_0
  - snowballstemmer=3.0.1=py39hca03da5_0
  - sphinx=7.3.7=py39hca03da5_0
  - sphinxcontrib-applehelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-devhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.1.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=2.0.0=pyhd3eb1b0_1
  - sphinxcontrib-serializinghtml=2.0.0=pyhd3eb1b0_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - superqt=0.7.3=py39hd096484_0
  - tbb=2021.8.0=h48ca7d4_0
  - tensorboard-data-server=0.7.0=py39ha6e5c4f_1
  - tensorboard-plugin-wit=1.8.1=py39hca03da5_0
  - termcolor=2.1.0=py39hca03da5_0
  - threadpoolctl=3.5.0=py39h33ce5c2_0
  - tifffile=2023.4.12=py39hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tomli=2.2.1=py39hca03da5_0
  - tomli-w=1.2.0=pyhd3eb1b0_0
  - toolz=1.0.0=py39hca03da5_0
  - torchvision=0.18.1=cpu_py39hb6554cd_0
  - tornado=6.4.1=py39h80987f9_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typer=0.9.0=py39hca03da5_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing-inspection=0.4.0=py39hca03da5_0
  - typing_extensions=4.12.2=pyha770c72_0
  - unicodedata2=15.1.0=py39h80987f9_0
  - vispy=0.14.3=py39h33df132_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=3.0.3=py39hca03da5_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py39h1a28f6b_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.11.0=py39h80987f9_0
  - zarr=2.13.3=py39hca03da5_0
  - zeromq=4.3.5=h313beb8_0
  - zfp=1.0.0=h313beb8_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstd=1.5.6=hb46c0d2_0
  - pip:
      - anyio==4.11.0
      - astor==0.8.1
      - bert==2.2.0
      - bert-tensorflow==1.0.4
      - bio==1.6.2
      - biothings-client==0.3.1
      - colorlog==6.10.1
      - contourpy==1.3.0
      - cycler==0.12.1
      - einops==0.8.0
      - erlastic==2.0.0
      - filelock==3.16.1
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - gprofiler-official==1.0.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.25.1
      - idna==3.8
      - importlib-resources==6.4.5
      - ipywidgets==8.1.8
      - jupyterlab-widgets==3.0.16
      - keras==3.5.0
      - keras-applications==1.0.8
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - lxml==6.0.2
      - manifold3d==3.2.1
      - mapbox-earcut==1.0.3
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - msgspec==0.19.0
      - mygene==3.2.2
      - namex==0.0.8
      - nodeenv==1.9.1
      - numpy==1.26.4
      - opencv-python==4.12.0.88
      - optree==0.12.1
      - pycollada==0.9.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - regex==2024.9.11
      - rich==13.8.1
      - rtree==1.4.1
      - safetensors==0.4.5
      - shapely==2.0.7
      - sniffio==1.3.1
      - svg-path==7.0
      - sympy==1.13.3
      - tensorboard==2.17.1
      - tensorflow==2.17.0
      - tensorflow-estimator==1.14.0
      - tensorflow-hub==0.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - tf-keras==2.17.0
      - tokenizers==0.20.0
      - torch==2.4.1
      - tqdm==4.66.5
      - transformers==4.45.1
      - trimesh==4.9.0
      - tzdata==2024.1
      - urllib3==2.2.3
      - vhacdx==0.0.9
      - viser==1.0.15
      - websockets==15.0.1
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yourdfpy==0.0.58
prefix: /Users/steveli/miniconda3/envs/ML
